travis:
  secure:
    BINSTAR_TOKEN: aThphK7er5Sh93QVHME5izgSslbrw17nDZrr1v2K1LRcpUC6Q4whgCxrOhhFU6Ljb9s88hCWJ6ofEgL2BS1fGvdrFoJn2cYWSyjsie00eh0RvFuYDxhTEwsjltUn53eS7FlBKxokzGtF9izB1798BpyxxU+NGwChFSF0zSVewv85pxIQ6tkofs5xDUiGMKvtGbjX6GSPDHnAdU0iJkrjb9YdySzGEMDmY7y2TJHANx8iGc7NDN/6TS/bth33dtuEFjLmcOUqxfmltdwDI+j8rcgSbvM3+XBX2wEzCYOv2Tg3QPcVGBoAPtbfdbfSeRB9Z0h56vLvGOJd3DcxN3iOENhp522cU9WTAwXfTfShI8swkuUfuld4Xxp2c2+azi03oNjHnmVy74KIjMootIL73YE5o88xleeU1vLzps7UfbqU33HKO+NHfdZwKxcqEfXCXeCKNlRbq6ACezN/mUXXPkmu0kfJq2epYlALAelk/KKRuL1d17KmPDXDzoFnUdJCKbuLAkEsTFCZgtVWXtAGDSmoPBFfWJ7xlDufdFbUQXDGYjP1sRcv8qoWLxy9b6t4W9vdZeS3XWYS3L2DYtNMTJJwzG5WVfJp0msMRUjLuBBvEMMh0T0FblBFmYUXg2b1+GUXxbEp8doJIsyyv5h/SdjzI2B9z+x3msctgWPE2eg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
